// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20251031125023_GetPersons_StoredProcedure")]
    partial class GetPersons_StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("0c5b9025-a178-422f-9772-b83cf42f3fba"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryID = new Guid("206418e0-f767-4689-bac9-b0aa7696e60a"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryID = new Guid("b7d4a259-c1df-42a1-b9cb-1d833d1580a3"),
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryID = new Guid("f7f1e057-cc8d-4c34-b03f-32387397daa2"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryID = new Guid("148fecc0-f5aa-43a1-9744-1da4289c7a5a"),
                            CountryName = "Australia"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("2f4322b9-d231-4d6c-89da-eb0821467fbb"),
                            Address = "Apt 841",
                            CountryID = new Guid("0c5b9025-a178-422f-9772-b83cf42f3fba"),
                            DateOfBirth = new DateTime(2009, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "toventon0@ucla.edu",
                            Gender = "Female",
                            PersonName = "Tory Oventon",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("a116271c-7443-4323-84c5-d41ba2d96be9"),
                            Address = "6th Floor",
                            CountryID = new Guid("148fecc0-f5aa-43a1-9744-1da4289c7a5a"),
                            DateOfBirth = new DateTime(1997, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rhessay1@jalbum.net",
                            Gender = "Female",
                            PersonName = "Rosy Hessay",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("3b372230-d9b4-4952-99f4-3e9369fa0db4"),
                            Address = "PO Box 5286",
                            CountryID = new Guid("f7f1e057-cc8d-4c34-b03f-32387397daa2"),
                            DateOfBirth = new DateTime(1992, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hfishlee2@ucoz.com",
                            Gender = "Male",
                            PersonName = "Holly Fishlee",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("b0da6468-792d-4649-b1dd-62d6f9c22735"),
                            Address = "Room 861",
                            CountryID = new Guid("206418e0-f767-4689-bac9-b0aa7696e60a"),
                            DateOfBirth = new DateTime(2015, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tpalleske3@weibo.com",
                            Gender = "Other",
                            PersonName = "Teresita Palleske",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("b4e88afa-ba23-4861-bc66-2deebc899239"),
                            Address = "2nd Floor",
                            CountryID = new Guid("f7f1e057-cc8d-4c34-b03f-32387397daa2"),
                            DateOfBirth = new DateTime(2013, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "byarrow4@utexas.edu",
                            Gender = "Female",
                            PersonName = "Brana Yarrow",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("3cd4ad95-b7d4-43a9-b1a8-c09a3ffe8612"),
                            Address = "Suite 59",
                            CountryID = new Guid("206418e0-f767-4689-bac9-b0aa7696e60a"),
                            DateOfBirth = new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nmccullen5@national.com",
                            Gender = "Female",
                            PersonName = "Nicola McCullen",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("0ecabf09-8d29-4cab-9593-ffda5c1016f0"),
                            Address = "PO Box 53534",
                            CountryID = new Guid("148fecc0-f5aa-43a1-9744-1da4289c7a5a"),
                            DateOfBirth = new DateTime(1995, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pharman4@github.com",
                            Gender = "Male",
                            PersonName = "Peyter Harman",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("1884cf5f-9cac-4d2e-8407-ae688f39adc8"),
                            Address = "Room 1638",
                            CountryID = new Guid("206418e0-f767-4689-bac9-b0aa7696e60a"),
                            DateOfBirth = new DateTime(2006, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethoma6@mozilla.com",
                            Gender = "Male",
                            PersonName = "Erroll Thoma",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("b32c879f-c578-4f6f-b6a6-de5069ae2f4b"),
                            Address = "Apt 1481",
                            CountryID = new Guid("0c5b9025-a178-422f-9772-b83cf42f3fba"),
                            DateOfBirth = new DateTime(2003, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sewebank7@blogs.com",
                            Gender = "Male",
                            PersonName = "Serge Ewebank",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("47f724a7-7851-46f5-8b1c-c3f3b9d29eb9"),
                            Address = "5th Floor",
                            CountryID = new Guid("b7d4a259-c1df-42a1-b9cb-1d833d1580a3"),
                            DateOfBirth = new DateTime(1990, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bchiverton2@ucsd.edu",
                            Gender = "Other",
                            PersonName = "Boothe Chiverton",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
